<a href="https://colab.research.google.com/github/NyssaRomana/IDCamp-Dicoding/blob/main/duasembilanmaret.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.4 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort, reviews_all

In [3]:
import pandas as pd  # Pandas untuk manipulasi dan analisis data
pd.options.mode.chained_assignment = None  # Menonaktifkan peringatan chaining
import numpy as np  # NumPy untuk komputasi numerik
seed = 0
np.random.seed(seed)  # Mengatur seed untuk reproduktibilitas
import matplotlib.pyplot as plt  # Matplotlib untuk visualisasi data
import seaborn as sns  # Seaborn untuk visualisasi data statistik, mengatur gaya visualisasi

import datetime as dt  # Manipulasi data waktu dan tanggal
import re  # Modul untuk bekerja dengan ekspresi reguler
import string  # Berisi konstanta string, seperti tanda baca
from nltk.tokenize import word_tokenize  # Tokenisasi teks
from nltk.corpus import stopwords  # Daftar kata-kata berhenti dalam teks

!pip install sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory  # Stemming (penghilangan imbuhan kata) dalam bahasa Indonesia
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory  # Menghapus kata-kata berhenti dalam bahasa Indonesia

from wordcloud import WordCloud  # Membuat visualisasi berbentuk awan kata (word cloud) dari teks

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.0 MB/s eta 0:00:00
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

In [4]:
import nltk  # Import pustaka NLTK (Natural Language Toolkit).
nltk.download('punkt')  # Mengunduh dataset yang diperlukan untuk tokenisasi teks.
nltk.download('stopwords')  # Mengunduh dataset yang berisi daftar kata-kata berhenti (stop words) dalam berbagai bahasa.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
scrapreview1 = reviews_all(
    'com.shopee.id',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT
)

scrapreview2 = reviews_all(
    'com.shopee.id',
    lang='id',
    country='id',
    sort=Sort.NEWEST
)

# Gabungkan
scrapreview = scrapreview1 + scrapreview2

# Ambil 12k
scrapreview = scrapreview[:12000]

In [23]:
# Menyimpan ulasan dalam file CSV
import csv

app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df.shape
app_reviews_df.head()
app_reviews_df.to_csv('ulasan_aplikasi.csv', index=False)

In [24]:
# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(scrapreview)

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape

In [25]:
# Menampilkan lima baris pertama dari DataFrame app_reviews_df
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,efe1d2ea-d52a-4018-bc64-871971ef8f6f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"padahal saya pelanggan setia shopee,tapi setel...",1,2,3.70.24,2026-03-25 04:54:07,"Hai kak Fens Iryanto, maaf ya udah buat risau ...",2026-03-24 10:23:17,3.70.24
1,9ca76e21-8ef2-4ce3-8eb0-090ecaf1d422,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasinya bagus, buat pesan beli barang pun ...",3,3,3.69.35,2026-03-17 22:12:47,"Hai kak Ardhyka Akasia, maaf banget buat kamu ...",2026-03-18 00:29:23,3.69.35
2,73cbf1f9-1b5b-481e-ac67-7332f555cb73,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sangat kecewa dengan layanan Shopee. Saya meng...,1,1,3.69.36,2026-03-23 15:39:08,"Hai kak Firza, mohon maaf atas ketidaknyamanan...",2026-03-23 17:08:39,3.69.36
3,faa4e342-881d-48b7-ad6f-a693f36ba1e0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"aplikasi Shopee sangat bagus, barang sesuai de...",5,2,3.69.32,2026-03-25 02:50:04,"Hai kak neolaka yulia, makasih ya buat bintang...",2026-03-25 04:08:47,3.69.32
4,934dc3d8-31b2-4064-81af-27c96214f6f4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Belanja dengan harapan harga murah malah dapat...,1,2,3.69.34,2026-03-23 08:29:57,"Hai kak , maaf ya sudah buat kamu gak nyaman t...",2026-03-23 09:18:44,3.69.34

In [26]:
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252000 entries, 0 to 251999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              252000 non-null  object
 1   userName              252000 non-null  object
 2   userImage             252000 non-null  object
 3   content               252000 non-null  object
 4   score                 252000 non-null  int64
 5   thumbsUpCount         252000 non-null  int64
 6   reviewCreatedVersion  206013 non-null  object
 7   at                    252000 non-null  datetime64[ns]
 8   replyContent          165276 non-null  object
 9   repliedAt             165276 non-null  datetime64[ns]
 10  appVersion            206013 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 21.1+ MB

In [27]:
# Ambil 10.000 data saja (cukup untuk nilai tinggi)
app_reviews_df = app_reviews_df.sample(n=10000, random_state=42)

In [28]:
app_reviews_df = app_reviews_df.dropna()

In [29]:
print("Jumlah data setelah sampling:", len(app_reviews_df))
app_reviews_df.head()

Jumlah data setelah sampling: 5418

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
75255,15aeb6aa-d1a9-4d60-a885-1758d3573586,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi udah berapa kali di uninstall terus d...,1,0,2.69.21,2022-04-18 17:20:16,"Hai kak, makasih buat feedbacknya. Terkait ken...",2022-04-19 01:13:58,2.69.21
154839,a6b28c99-0878-444c-8e5f-a34dd5abffeb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"apa ini, capek masukin no.rek tdk berhasil, se...",1,1,3.31.18,2025-02-15 13:22:08,"hai kak, maaf ya udah bikin kamu risau terkait...",2024-08-04 15:07:43,3.31.18
59774,8a72c34a-62e8-4daa-bd60-0942d77b0f8b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Kecewa sekali dengan shopee, toko sy tiba-tiba...",1,983,2.60.12,2020-09-27 21:00:00,"Halo kak, maaf ya udah bikin kamu resah. Pasti...",2020-09-27 22:42:07,2.60.12
63788,29c18fd1-dc43-41bc-8404-6df1a4db17e4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,aplikasi nya sangat tidak membantu konsumen......,1,4,3.59.38,2025-10-01 12:42:53,"Hai kak Amin St, mohon maaf atas ketidaknyaman...",2025-10-01 13:26:30,3.59.38
239302,e864312e-93b1-4f43-b278-68b475cf8c52,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,aplikasinya bisa hemat uang ku terpercaya dan ...,5,1,3.44.21,2025-04-03 10:35:14,"Hi Kak Eka , terima kasih komentar dan bintang...",2025-04-03 11:20:57,3.44.21

In [30]:
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5418 entries, 75255 to 178094
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              5418 non-null   object
 1   userName              5418 non-null   object
 2   userImage             5418 non-null   object
 3   content               5418 non-null   object
 4   score                 5418 non-null   int64
 5   thumbsUpCount         5418 non-null   int64
 6   reviewCreatedVersion  5418 non-null   object
 7   at                    5418 non-null   datetime64[ns]
 8   replyContent          5418 non-null   object
 9   repliedAt             5418 non-null   datetime64[ns]
 10  appVersion            5418 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 507.9+ KB